# Generated by Django 5.0.4 on 2024-05-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
    ]
