# Generated by Django 5.0.4 on 2024-05-20 06:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_username_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Gender',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, null=True)),
                ('college', models.CharField(blank=True, null=True)),
                ('specilization', models.CharField(blank=True, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='account.candidate')),
            ],
        ),
    ]
