# Generated by Django 5.0.4 on 2024-05-20 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_candidate_gender_candidate_completed_candidate_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='candidate',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
