# Generated by Django 5.0.4 on 2024-05-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_education_candidate_education_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
