# Generated by Django 5.0.4 on 2024-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'candidate'), ('employer', 'employer'), ('admin', 'admin')], max_length=10),
        ),
    ]
