# Generated by Django 5.0.4 on 2024-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('candidate', 'candidate'), ('employer', 'employer'), ('admin', 'admin')], max_length=10, null=True),
        ),
    ]
