# Generated by Django 5.0.4 on 2024-05-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_candidate_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='company_pic')),
                ('headquarters', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_name', models.CharField(blank=True, max_length=40, null=True)),
                ('hr_phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('website_link', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
