# Generated by Django 5.0.4 on 2024-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_candidate_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
