# Generated by Django 5.0.4 on 2024-07-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='hr_email',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='hr_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='hr_phone',
        ),
    ]
