# Generated by Django 5.0.4 on 2024-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_interviewshedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewshedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Selected', 'Selected'), ('Canceled', 'Canceled'), ('You are late', 'You are late')], default='Waiting', max_length=20),
        ),
    ]
