# Generated by Django 5.0.4 on 2024-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0003_interviewshedule_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Upcoming', 'Upcoming'), ('Canceled', 'Canceled'), ('You missed', 'You missed')], default='Upcoming', max_length=20),
        ),
    ]
