# Generated by Django 5.0.4 on 2024-06-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0005_alter_interviewshedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Selected', 'Selected'), ('Upcoming', 'Upcoming'), ('You missed', 'You missed')], default='Upcoming', max_length=20),
        ),
    ]
