# Generated by Django 5.0.4 on 2024-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0007_alter_interviewshedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('You missed', 'You missed'), ('Canceled', 'Canceled'), ('Selected', 'Selected')], default='Upcoming', max_length=20),
        ),
    ]
