# Generated by Django 5.0.4 on 2024-06-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0008_alter_interviewshedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Selected', 'Selected'), ('You missed', 'You missed'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=20),
        ),
    ]
