# Generated by Django 5.0.4 on 2024-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0012_alter_interviewshedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('You missed', 'You missed'), ('Rejected', 'Rejected'), ('Upcoming', 'Upcoming'), ('Canceled', 'Canceled'), ('Selected', 'Selected')], default='Upcoming', max_length=20),
        ),
    ]
