# Generated by Django 5.0.4 on 2024-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0013_alter_interviewshedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewshedule',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Upcoming', 'Upcoming'), ('Selected', 'Selected'), ('You missed', 'You missed'), ('Canceled', 'Canceled')], default='Upcoming', max_length=20),
        ),
    ]
