# Generated by Django 5.0.4 on 2024-06-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='application',
        ),
    ]
