# Generated by Django 5.0.4 on 2024-06-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_candidate_place'),
        ('chat', '0002_rename_sender_chatmessage_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='employer',
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='account.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='account.employer')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chatroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
