# Generated by Django 5.0.4 on 2024-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpJobs', '0002_jobs_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='posteDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
