# Generated by Django 5.0.4 on 2024-05-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpJobs', '0003_alter_jobs_postedate'),
        ('account', '0013_employer_hr_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpJobs.jobs')),
            ],
        ),
    ]
