# Generated by Django 5.0.4 on 2024-05-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpJobs', '0004_savedjobs'),
        ('account', '0013_employer_hr_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Application Send', 'Application Send'), ('Application Viewd', 'Application Viewd'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Application Send', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpJobs.jobs')),
            ],
        ),
    ]
